name: Static Site
on:
  push:
    branches: main
jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node
      - name: Dependencies
        run: npm ci
      - name: Render Site
        run: npm run build