name: Static Site
on:
  push:
    branches: main
permissions:
  id-token: write
  contents: read
jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Dependencies
        run: npm ci
      - name: Render Site
        run: npm run build
      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_UPLOAD_S3 }}
            role-session-name: GitHub_to_AWS_via_FederatedOIDC
            aws-region: us-east-2
      - name: deploy
        if: github.ref == 'refs/heads/main'
        run: |
          find ./_site/ \( -iname '*.html' -o -iname '*.css' -o -iname '*.js' -o -iname '*.json' -o -iname '*.svg' -o -iname '*.xml' \) -exec brotli {} \; -exec mv {}.br {} \;
          aws s3 sync --delete --cache-control 'public,max-age=31536000,immutable' ./_site/ s3://www.pureooze.com --content-encoding 'br' --exclude '*.*' --include '*.html' --include '*.js' --include '*.json' --include '*.csv' --include '*.svg' --include '*.xml'
          aws s3 sync --delete --cache-control 'public,max-age=31536000,immutable' ./_site/ s3://www.pureooze.com --exclude '*.html' --exclude '*.css' --exclude '*.js' --exclude '*.json' --exclude '*.csv' --exclude '*.svg' --exclude '*.xml' --exclude '*.woff2'
